FROM rbekker87/armhf-alpine:3.7

RUN addgroup -S redis && adduser -S -G redis redis && \
    apk update && apk add --no-cache 'su-exec>=0.2' redis && \
    mkdir /data && chown -R redis:redis /var/lib/redis /data

WORKDIR /data

CMD ["su-exec", "redis", "/usr/bin/redis-server"]
